### ISSUE TITLE
Questionable Domain Layer

### ISSUE THREAD

**Issue by md-redwan-hossain** [WorldWideWest/dotnet-template#26]
Why the domain layer is tightly coupled with third party packages? Aren't these libraries belong to the Infrastructure layer? The domain should be remain pure and agnostic of any dependencies.

```
<PackageReference Include="Azure.Communication.Email" Version="1.0.1" />
<PackageReference Include="Duende.IdentityServer" Version="6.3.8" />
<PackageReference Include="FluentValidation" Version="11.9.0" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.2" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
```

**Comment by WorldWideWest** [comment]
Some of these definitly need  to be removed because as I looked at the code they aren’t even used, but at the domain of this project currently is the aspnet user and creating a model without installing the packege wouldn’t be possible.

so this issue will be used to clean up the domain layer

**Comment by WorldWideWest** [comment]
@md-redwan-hossain the issues will be addressed in this branch, [code-improvements](https://github.com/WorldWideWest/dotnet-template/tree/feature/code-improvements) currently I'am testing out the changes to make sure everything works, to then make a PR and marge it to main

**Comment by WorldWideWest** [comment]
The changes have been tested and merged to main
